name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Check out submodules
      run: git submodule update --init
    - name: Build for yggdrasil
      run: make DEVICE=yggdrasil -j$(nproc --all)
    
